//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metars.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Metars.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string Error_Occured {
            get {
                return ResourceManager.GetString("Error_Occured", resourceCulture);
            }
        }
        
        internal static string Metars {
            get {
                return ResourceManager.GetString("Metars", resourceCulture);
            }
        }
        
        internal static string Get_Metar {
            get {
                return ResourceManager.GetString("Get_Metar", resourceCulture);
            }
        }
        
        internal static string Identifier_Entry_Placeholder {
            get {
                return ResourceManager.GetString("Identifier_Entry_Placeholder", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string Saved_Searches {
            get {
                return ResourceManager.GetString("Saved_Searches", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        internal static string Last_Updated {
            get {
                return ResourceManager.GetString("Last_Updated", resourceCulture);
            }
        }
        
        internal static string Flight_Rules {
            get {
                return ResourceManager.GetString("Flight_Rules", resourceCulture);
            }
        }
        
        internal static string Altimeter {
            get {
                return ResourceManager.GetString("Altimeter", resourceCulture);
            }
        }
        
        internal static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        internal static string Dewpoint {
            get {
                return ResourceManager.GetString("Dewpoint", resourceCulture);
            }
        }
        
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        internal static string Wind_Direction {
            get {
                return ResourceManager.GetString("Wind_Direction", resourceCulture);
            }
        }
        
        internal static string Wind_Speed {
            get {
                return ResourceManager.GetString("Wind_Speed", resourceCulture);
            }
        }
        
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        internal static string Runways {
            get {
                return ResourceManager.GetString("Runways", resourceCulture);
            }
        }
        
        internal static string More_Info {
            get {
                return ResourceManager.GetString("More_Info", resourceCulture);
            }
        }
        
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        internal static string Elevation {
            get {
                return ResourceManager.GetString("Elevation", resourceCulture);
            }
        }
        
        internal static string Check_Connection {
            get {
                return ResourceManager.GetString("Check_Connection", resourceCulture);
            }
        }
    }
}
